language: ruby
rvm: 
    - 2.0.0-p648
    - 2.5.1
cache: bundler
before_install: gem install bundler
before_script:
    # Useful for reference while reviewing travis failures
    - xcrun simctl list -j devices
script:
  - bundle exec rake
